<?xml version="1.0" encoding="utf-8"?><Database Name="BodyLogDB" Class="AccountsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BodyLogDB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BodyLogDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Account_Food" Member="Food" ThisKey="Id" OtherKey="Id" Type="Food" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Foods" Member="Foods">
    <Type Name="Food">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="calories" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Account_Food" Member="Account" ThisKey="Id" OtherKey="Id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Tests">
    <Type Name="Test">
      <Column Name="test" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>